steps:
  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: [
            'build',
            '-t',
            'europe-west1-docker.pkg.dev/blissful-canyon-417604/Images for cloud-build-image1/quickstart-image:v1',
            '-t',
            'europe-west1-docker.pkg.dev/blissful-canyon-417604/Images for cloud-build-image1/quickstart-image:v2',
            '--cache-from',
            'us-central1-docker.pkg.dev/blissful-canyon-417604/Images for cloud-build-image1/quickstart-image:v2',
            '.'
          ]

  # Docker push to Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push',  'us-central1-docker.pkg.dev/pub-demo-cb-ar/python-repo/my-app:${SHORT_SHA}']

# Store images in Google Artifact Registry 
images:
  - us-central1-docker.pkg.dev/pub-demo-cb-ar/python-repo/my-app:${SHORT_SHA}
  - us-central1-docker.pkg.dev/pub-demo-cb-ar/python-repo/my-app:latest
